spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:mysql://127.0.0.1:3306/mybatisplus_fill_metainfo?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: roottest

mybatis-plus:
  global-config:
    db-config:
      id-type: id_worker
      capital-mode: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl