# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:mysql://127.0.0.1:3306/mybatisplus_ar?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: roottest


# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.ar: debug
# MyBatis-Plus 配置该演示无
